// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARKcfJoPqlOg9JYWX5rib91yvsyD5eQAc',
    appId: '1:114641901575:web:1f83c67b50f105da73f2a2',
    messagingSenderId: '114641901575',
    projectId: 'flutter-chat-app-27f19',
    authDomain: 'flutter-chat-app-27f19.firebaseapp.com',
    storageBucket: 'flutter-chat-app-27f19.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpty3E_weXpLHi6Uy0gusOLBv1yqwiryc',
    appId: '1:114641901575:android:f45b50b41ca1e09b73f2a2',
    messagingSenderId: '114641901575',
    projectId: 'flutter-chat-app-27f19',
    storageBucket: 'flutter-chat-app-27f19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCALg2f_0422AxHspxWOWWhonR7uwe9Kt8',
    appId: '1:114641901575:ios:0f2bee6ed4ddcbf173f2a2',
    messagingSenderId: '114641901575',
    projectId: 'flutter-chat-app-27f19',
    storageBucket: 'flutter-chat-app-27f19.appspot.com',
    iosBundleId: 'com.example.chattApp',
  );
}
